### Create new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "newabc@gmail.com",
    "password": "123"
}

### get user
GET  http://localhost:3000/auth/1

### get user by email
GET  http://localhost:3000/auth? email=abc@gmail.com

### remove user by id
DELETE   http://localhost:3000/auth/1
